List<Map<String,dynamic>> sampleProject=[
  {
    'id':1,
    'name': 'MT-G',
    'description':'Make a statement of timeless elegance with our Elegant Men\'s Chronograph Watch, the perfect accessory for the modern gentleman who appreciates both style and functionality. Elevate your wristwear game and command attention with every gesture',
    'image':'assets/image/watch.jpeg',
    'image2':'assets/image/watch.jpeg',
    'price':'2000',
    'brand name':'G-SHOCK',
  },
  {
    'id':2,
    'name':'GA-1a2',
    'brand name':'G-SHOCK',
    'description':'Make a statement of timeless elegance with our Elegant Men\'s Chronograph Watch, the perfect accessory for the modern gentleman who appreciates both style and functionality. Elevate your wristwear game and command attention with every gesture',
    'image':'assets/image/watch.jpeg',
    'image2':'assets/image/watch.jpeg',
    'price':'3000',
  },
  {
    'id':3,
    'name':'MudMaster',
    'description':'Make a statement of timeless elegance with our Elegant Men\'s Chronograph Watch, the perfect accessory for the modern gentleman who appreciates both style and functionality. Elevate your wristwear game and command attention with every gesture',
    'image':'assets/image/watch.jpeg',
    'image2':'assets/image/watch.jpeg',
    'price':'2000',
    'brand name':'G-SHOCK',
  },
  {
    'id':4,
    'name':'Dw-5600',
    'description':'Make a statement of timeless elegance with our Elegant Men\'s Chronograph Watch, the perfect accessory for the modern gentleman who appreciates both style and functionality. Elevate your wristwear game and command attention with every gesture',
    'image':'assets/image/watch.jpeg',
    'price':'2000',
    'brand name':'G-SHOCK',
  },
  {
    'id':5,
    'name':'MTG-B30000',
    'description':'Make a statement of timeless elegance with our Elegant Men\'s Chronograph Watch, the perfect accessory for the modern gentleman who appreciates both style and functionality. Elevate your wristwear game and command attention with every gesture',
    'image':'assets/image/watch.jpeg',
    'price':'18000',
    'brand name':'G-SHOCK',
  },

];